# Generated by Django 5.2.4 on 2025-12-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotserialnumber',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotserialnumber',
            name='lot_number',
            field=models.CharField(db_index=True, help_text='The batch or serial number', max_length=100),
        ),
    ]
