# Generated by Django 5.2.4 on 2026-01-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_lotserialnumber_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='stock.warehouse'),
        ),
    ]
