# Generated by Django 5.2.4 on 2025-10-07 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped to Supplier'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged Goods'), ('expired', 'Expired Goods'), ('wrong_item', 'Wrong Item Received'), ('quality_issue', 'Quality Issue'), ('overstock', 'Overstock'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_transferred', models.DecimalField(decimal_places=2, default=0, help_text='The actual quantity sent from the source warehouse.', max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, help_text='The actual quantity received at the destination warehouse.', max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('in_transit', 'In Transit'), ('received', 'Received')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Transfer Request',
                'verbose_name_plural': 'Stock Transfer Requests',
                'db_table': 'inventory_stock_transfer_request',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, help_text="Supplier's internal product code", max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at which this product is purchased from the supplier', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='partners.supplier')),
            ],
            options={
                'verbose_name_plural': 'Product Suppliers',
                'db_table': 'inventory_productsupplier',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('purchase_request', 'Purchase Request'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='purchase_request', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='partners.supplier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
