# Generated by Django 5.2.4 on 2025-10-07 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
        ('purchase', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='original_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='partners.supplier'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='lot_serial',
            field=models.ForeignKey(blank=True, help_text='The specific lot being returned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotserialnumber'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasereturn'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_lot',
            field=models.ForeignKey(blank=True, help_text='The specific lot from which stock was dispatched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dispatches', to='stock.lotserialnumber'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product', 'supplier')},
        ),
    ]
