# Generated by Django 5.2.4 on 2025-10-19 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_billpayment_credit_applied_and_more'),
        ('partners', '0001_initial'),
        ('purchase', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Applied', 'Applied'), ('Cancelled', 'Cancelled')], default='Available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applied_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='ap.billpayment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='purchase.purchasereturn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='partners.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Credit Note',
                'verbose_name_plural': 'Supplier Credit Notes',
            },
        ),
    ]
