# Generated by Django 5.2.4 on 2025-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_suppliercreditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='return_type',
            field=models.CharField(choices=[('credit', 'Return for Credit'), ('exchange', 'Return for Exchange')], default='credit', max_length=10, verbose_name='Return Type'),
        ),
    ]
