# Generated by Django 5.2.4 on 2025-11-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchasereturn_return_type'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='received_lot_serial',
            field=models.ForeignKey(blank=True, help_text='The new lot received as exchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_as_exchange_item', to='stock.lotserialnumber'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped to Supplier'), ('waiting_replacement', 'Waiting for Replacement'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='lot_serial',
            field=models.ForeignKey(blank=True, help_text='The specific lot being returned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_item', to='stock.lotserialnumber'),
        ),
    ]
