# Generated by Django 5.2.4 on 2026-01-06 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase (Debit)'), ('reload', 'Reload/Issue (Credit)'), ('refund', 'Refund (Credit)')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Order ID or Note', max_length=100)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketing.giftcard')),
            ],
        ),
    ]
