# Generated by Django 5.2.4 on 2026-01-08 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum percentage discount this user can provide.', max_digits=5),
        ),
    ]
