# Generated by Django 5.2.4 on 2026-01-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('pos', '0002_posorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderpayment',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='marketing.giftcard'),
        ),
    ]
