# Generated by Django 5.2.4 on 2026-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_posorderpayment_gift_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
