# Generated by Django 5.2.4 on 2025-10-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_cost', to='sales.salesorder'),
        ),
    ]
