"""
Django settings for inventory_system project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'dbbackup',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'axes',

    # My Custom Apps
    'inventory_system',
    'products.apps.ProductsConfig',
    'partners.apps.PartnersConfig',
    'stock.apps.StockConfig',
    'purchase.apps.PurchaseConfig',
    'sales.apps.SalesConfig',
    'pos.apps.PosConfig',
    'costing.apps.CostingConfig',
    'reports',
    'accounts.apps.AccountsConfig',
    'management',
    'marketing',

    'finance.apps.FinanceConfig',
    'finance.gl.apps.GlConfig',
    'finance.ap.apps.ApConfig',
    'finance.ar.apps.ArConfig',
    'finance.banking.apps.BankingConfig',
    'finance.assets.apps.AssetsConfig',
    'finance.cash.apps.CashConfig',
    'finance.investments.apps.InvestmentsConfig',
    'hrm',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'management.middleware.IPWhitelistMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'inventory_system', 'templates'),
            os.path.join(BASE_DIR, 'products', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table', # এই নামেই ডাটাবেসে একটি টেবিল তৈরি হবে
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Qatar'#'UTC' হবে যদি আমাদের লোকাল টাইম জোন সেট করতে চাই
USE_I18N = True
USE_TZ = True

# Static & Media Files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_production')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model & Login/Logout redirects
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# DBBackup Settings (লোকাল ব্যাকআপের জন্য)
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR, 'backups')}

# Custom Global Constants
DEFAULT_CURRENCY_SYMBOL = 'QAR '

# Password Hashers (Argon2 first, fallback to others)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Session & CSRF Security
SESSION_COOKIE_SECURE = True          # কুকি শুধু HTTPS এ পাঠানো হবে
CSRF_COOKIE_SECURE = True             # CSRF কুকি শুধু HTTPS এ পাঠানো হবে
SESSION_COOKIE_HTTPONLY = True        # JavaScript session cookie পড়তে পারবে না
CSRF_COOKIE_HTTPONLY = True           # JavaScript CSRF cookie পড়তে পারবে না
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # ব্রাউজার বন্ধ হলে লগআউট হবে
SESSION_COOKIE_AGE = 3600             # সেশন 60 মিনিট পর auto expire হবে (সেকেন্ডে)

# IP Whitelisting Settings
ALLOWED_IPS = [
    '127.0.0.1',  # লোকাল ডেভেলপমেন্টের জন্য
    '192.168.1.101', # অফিসের একটি নির্দিষ্ট কম্পিউটারের আইপি 
    '203.0.113.5',   # অন্য কোনো শাখার পাবলিক আইপি  এড্রেস আপডেট করে দিলে হবে।
]

# Email Configuration for Password Reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # ইমেইল অ্যাড্রেস .env ফাইলে আপডেট করতে হবে
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') # জিমেইল অ্যাপ পাসওয়ার্ড আপাতা এটা পরে আমাদের হোস্টিং এর মেইল ব্যবহার করবো। .env ফাইলে আপডেট করতে হবে।

# যে ইমেইল থেকে ব্যবহারকারী ইমেইল পাবে
DEFAULT_FROM_EMAIL = 'haymijan@gmail.com'

# Security Settings for Production
# নিচের সেটিংসগুলো তখনই কাজ করবে যখন DEBUG=False থাকবে
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Axes (Brute-force protection) Settings
AXES_FAILURE_LIMIT = 5  # ৫ বার ভুল চেষ্টার পর ব্লক হবে
AXES_COOLOFF_TIME = 0.25 # ১৫ মিনিটের জন্য ব্লক থাকবে (0.25 hours)
AXES_LOCKOUT_TEMPLATE = '404.html' # ব্লক হলে কোন পেজ দেখাবে
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # Axes backend
    'django.contrib.auth.backends.ModelBackend', # Default Django backend
]

# ওরিডো এসএমএস

OOREDOO_SMS_URL = config('OOREDOO_SMS_URL')
OOREDOO_CUSTOMER_ID = config('OOREDOO_CUSTOMER_ID')
OOREDOO_USERNAME = config('OOREDOO_USERNAME')
OOREDOO_PASSWORD = config('OOREDOO_PASSWORD')
OOREDOO_ORIGINATOR = config('OOREDOO_ORIGINATOR')