# Generated by Django 5.2.4 on 2025-10-07 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='The branch/warehouse from which the sale was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='lot_sold_from',
            field=models.ForeignKey(blank=True, help_text='The specific lot this item was sold from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotserialnumber'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_order',
            field=models.ForeignKey(help_text='The original sales order being returned.', on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='lot_sold_from',
            field=models.ForeignKey(blank=True, help_text='The specific lot this item was returned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotserialnumber'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn'),
        ),
    ]
