# Generated by Django 5.2.4 on 2025-10-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='return_type',
            field=models.CharField(choices=[('credit', 'Adjust Credit / No Refund'), ('cash_refund', 'Cash Refund Required')], default='credit', help_text='Specify if a cash refund is required for this return.', max_length=20),
        ),
    ]
