# Generated by Django 5.2.4 on 2026-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesreturn_return_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit at the time of sale.', max_digits=10),
        ),
    ]
