# Generated by Django 5.2.4 on 2026-01-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorderitem_cost_price'),
        ('stock', '0003_inventorytransaction_from_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity allocated from this specific lot', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.lotserialnumber')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'inventory_sales_order_item_allocation',
            },
        ),
    ]
