# Generated by Django 5.2.4 on 2026-01-08 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesorderitemallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount rounded off from the total (e.g., 0.05)', max_digits=10),
        ),
    ]
