# Generated by Django 5.2.4 on 2026-01-11 17:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_paymentmethod_type'),
        ('sales', '0007_salesorder_round_off_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_note',
            field=models.CharField(blank=True, help_text='Gift Card Code or Reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='selected_payment_method',
            field=models.ForeignKey(blank=True, help_text='Method used for manual payment entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_by_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_by_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('out_for_delivery', 'Out For Delivery'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
