# Generated by Django 5.2.4 on 2026-01-13 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_paymentmethod_type'),
        ('sales', '0008_salesorder_payment_note_salesorder_payment_status_and_more'),
        ('stock', '0003_inventorytransaction_from_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitemallocation',
            old_name='created_at',
            new_name='allocated_at',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='lot_sold_from',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='user',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_order_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the order', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='selected_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='banking.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing (Warehouse)'), ('packaging', 'Packaging'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesorderitemallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='reason',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_type',
            field=models.CharField(choices=[('refund', 'Refund (Money Back)'), ('exchange', 'Exchange (Credit/Replace)')], default='refund', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='lot_sold_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotserialnumber'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='salesorder',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salesorderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salesorderitemallocation',
            table=None,
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID or Check No', max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.paymentmethod')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('packaging', 'In Packaging'), ('shipped', 'Shipped / Out for Delivery'), ('delivered', 'Delivered')], default='packaging', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.warehouse')),
            ],
        ),
    ]
