# Generated by Django 5.2.4 on 2026-01-15 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_created_at_salesorderitemallocation_allocated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount rounded off from the total (e.g., 0.05)', max_digits=10),
        ),
    ]
