# Generated by Django 5.2.4 on 2026-01-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0011_salesreturn_customer_salesreturn_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesreturn', to='partners.customer'),
        ),
    ]
