# Generated by Django 5.2.4 on 2026-01-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_giftcardtransaction'),
        ('sales', '0012_alter_salesreturn_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='issued_gift_card',
            field=models.ForeignKey(blank=True, help_text='Fulfillment এর সময় এই ফিল্ডটি পূরণ করতে হবে', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.giftcard'),
        ),
    ]
