# Generated by Django 5.2.4 on 2025-12-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'verbose_name_plural': 'Units of Measure'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasurecategory',
            options={'verbose_name_plural': 'UoM Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='rounding',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unitofmeasurecategory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchase_uom', to='products.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sale_uom', to='products.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracking_method',
            field=models.CharField(choices=[('none', 'No Tracking'), ('lot', 'By Lot'), ('serial', 'By Serial Number')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_default_uom', to='products.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.unitofmeasurecategory'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='ratio',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='short_code',
            field=models.CharField(default='pc', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='unitofmeasure',
            table=None,
        ),
        migrations.AlterModelTable(
            name='unitofmeasurecategory',
            table=None,
        ),
    ]
