# Generated by Django 5.2.4 on 2026-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_created_at_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_card_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Only applicable if product type is Gift Card. This is the balance the customer gets.', max_digits=10, verbose_name='Gift Card Value'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('standard', 'Standard Product'), ('service', 'Service'), ('gift_card', 'Gift Card')], default='standard', help_text="Select 'Gift Card' if this product generates a voucher code.", max_length=20, verbose_name='Product Type'),
        ),
    ]
